// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mslgsxvoliqbljkxbdrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zbGdzeHZvbGlxYmxqa3hiZHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5Mjg4NDEsImV4cCI6MjA3NDUwNDg0MX0.qTBdrtxcYzZPMCKM7DPU1JfBNxUlmCFvGWFxRhS3AeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});